// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NOPAINNOGAIN.Data;

namespace NOPAINNOGAIN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220902131858_TabelaSistemaGR")]
    partial class TabelaSistemaGR
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
         
        }
    }
}
